# .streamlit/config.toml

[server]
fileWatcherType = "none"


[theme]
base="light"
primaryColor="#1f4fbc"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f5f7fb"
textColor="#111827"
font="sans serif"
